import { useState } from 'react'
import toast from 'react-hot-toast'
import { MagnifyingGlassIcon, PaperAirplaneIcon } from '@heroicons/react/24/outline'
import LoadingSpinner from './LoadingSpinner'

export default function QueryInterface() {
  const [query, setQuery] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [response, setResponse] = useState(null)

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!query.trim()) return

    setIsLoading(true)
    
    // Simulate API call
    setTimeout(() => {
      setResponse({
        answer: `This is a demo response to your query: "${query}". In a real implementation, this would be generated by AutoRAG using your document knowledge base and external search if needed.`,
        sources: [
          { name: 'Document 1.pdf', relevance: 0.92 },
          { name: 'Document 3.pdf', relevance: 0.87 },
          { name: 'External: Wikipedia', relevance: 0.75 }
        ],
        trustScore: 0.89,
        processingTime: '1.2s'
      })
      setIsLoading(false)
      toast.success('Query processed (demo)')
    }, 2000)
  }

  const handleClear = () => {
    setQuery('')
    setResponse(null)
  }

  return (
    <div className="group rounded-3xl border border-gray-200/50 bg-gradient-to-br from-white to-blue-50/30 p-8 shadow-xl transition-all duration-500 hover:shadow-2xl hover:-translate-y-2">
      <div className="flex items-center gap-3 mb-6">
        <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center group-hover:scale-110 transition-transform duration-300">
          <MagnifyingGlassIcon className="h-5 w-5 text-white" />
        </div>
        <h3 className="text-xl font-bold text-gray-900">Test AutoRAG Query</h3>
        <div className="ml-auto">
          <div className="flex items-center gap-1">
            <div className="h-2 w-2 rounded-full bg-green-400 animate-pulse" />
            <span className="text-xs text-gray-500">Live</span>
          </div>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="relative">
          <div className="flex space-x-3">
            <div className="relative flex-1">
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Ask a question about your documents..."
                className="w-full rounded-2xl border-2 border-gray-200 bg-white/80 px-6 py-4 text-sm backdrop-blur-sm transition-all duration-300 focus:border-blue-500 focus:ring-4 focus:ring-blue-500/20 focus:bg-white disabled:opacity-50"
                disabled={isLoading}
              />
              <div className="absolute inset-y-0 right-4 flex items-center pointer-events-none">
                <div className="text-gray-400">
                  {query.length > 0 && (
                    <span className="text-xs bg-gray-100 px-2 py-1 rounded-full">
                      {query.length} chars
                    </span>
                  )}
                </div>
              </div>
            </div>
            <button
              type="submit"
              disabled={isLoading || !query.trim()}
              className="group/btn relative overflow-hidden rounded-2xl bg-gradient-to-r from-blue-600 to-purple-600 px-6 py-4 text-sm font-semibold text-white shadow-lg transition-all duration-300 hover:shadow-xl hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
            >
              <div className="absolute inset-0 bg-gradient-to-r from-purple-600 to-blue-600 opacity-0 group-hover/btn:opacity-100 transition-opacity duration-300" />
              <div className="relative flex items-center">
                {isLoading ? (
                  <>
                    <LoadingSpinner size="sm" className="mr-2" />
                    <span>Processing...</span>
                  </>
                ) : (
                  <>
                    <PaperAirplaneIcon className="h-4 w-4 mr-2 group-hover/btn:rotate-12 transition-transform duration-300" />
                    <span>Ask</span>
                  </>
                )}
              </div>
            </button>
          </div>
        </div>
      </form>

      {isLoading && (
        <div className="mt-4 p-4 bg-blue-50 rounded-lg">
          <div className="flex items-center">
            <LoadingSpinner size="sm" className="mr-3" />
            <div className="text-sm text-blue-700">
              Processing your query with AutoRAG...
            </div>
          </div>
        </div>
      )}

      {response && (
        <div className="mt-6 space-y-4">
          <div className="p-4 bg-green-50 rounded-lg border border-green-200">
            <div className="flex items-center justify-between mb-2">
              <h4 className="text-sm font-medium text-green-900">Response</h4>
              <div className="flex items-center space-x-4 text-xs text-green-700">
                <span>Trust Score: {response.trustScore}</span>
                <span>Time: {response.processingTime}</span>
              </div>
            </div>
            <p className="text-sm text-green-800">{response.answer}</p>
          </div>

          <div className="p-4 bg-gray-50 rounded-lg">
            <h4 className="text-sm font-medium text-gray-900 mb-2">Sources</h4>
            <div className="space-y-2">
              {response.sources.map((source, index) => (
                <div key={index} className="flex items-center justify-between text-sm">
                  <span className="text-gray-700">{source.name}</span>
                  <span className="text-gray-500">Relevance: {source.relevance}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="flex justify-end">
            <button
              type="button"
              onClick={handleClear}
              className="text-sm text-gray-500 hover:text-gray-700"
            >
              Clear Results
            </button>
          </div>
        </div>
      )}
    </div>
  )
}